### ISSUE TITLE
网易 - 动态换肤答疑 | 西门博客 - 让技术更透明、让开发更简单！

### ISSUE THREAD

**Issue by cnmen** [cnmen/cnmen.github.io#24]
https://www.cmonbaby.com/posts/netease_skin_question.html 

 作者：彭老师 日期：2019-07-17 类型：Android 说明：本文源于彭老师手写摘要，如需转载请带上链接或注明出处！    1、CustomXXX可以不继承父类（目的只为了截取控件）2、onCreateView方法执行了两次：从setContentView()跟进去：LayoutInflater   492 - 730 - 772 执行了一次LayoutInflater   515 -

**Comment by suchen2** [comment]
一位不愿意露面的人前来捧场——牛逼

**Comment by cybkw** [comment]
皮肤包删除了classes.dex文件，换肤失败，无法找到包名。

System.err: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageInfo.packageName' on a null object reference
        at com.netease.skin.library.SkinManager.loaderSkinResources(SkinManager.java:99)

相同的存档路径，未删除任何文件的皮肤包换肤成功。

**Comment by cnmen** [comment]
> @cybkw
> 皮肤包删除了classes.dex文件，换肤失败，无法找到包名。
> 
> System.err: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageInfo.packageName' on a null object reference
>         at com.netease.skin.library.SkinManager.loaderSkinResources(SkinManager.java:99)
> 
> 相同的存档路径，未删除任何文件的皮肤包换肤成功。

我猜你做了解压动作，再把文件夹再压缩。如果是这样的肯定是不行的。
之前1901班刘金伟同学就犯过这个错。
你可以用解压软件打开它删除，千万不要解压成文件夹！
